name: ketub_platform
description: An epub reader app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.3.0+23

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lorem_ipsum:
  path_provider:
  sqflite: any
  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.2
  flutter_colorpicker: ^1.0.3
  flutter_bloc: ^8.1.3
  epub_parser: ^3.0.1
  flutter_svg: ^1.0.3
  xml: ^5.0.2
  scrollable_positioned_list: ^0.3.8
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  shared_preferences: ^2.0.6
  http: ^1.1.0
  audioplayers: ^5.2.1
  audio_service: ^0.18.12
  just_audio_platform_interface: ^4.2.2
  just_audio_mpv: ^0.1.7
  rxdart: ^0.27.7
  just_audio: ^0.9.36
  just_audio_background: any
  audio_session: ^0.1.14
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  url_launcher: ^6.0.20
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#274194"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/css/ketubStyle.css
    - assets/images/
    - assets/epubs/
    - assets/icons/
    - assets/databases/book_list.db
  fonts:
    - family: font1
      fonts:
        - asset: assets/fonts/font1.ttf
    - family: font2
      fonts:
        - asset: assets/fonts/font2.ttf
    - family: font3
      fonts:
        - asset: assets/fonts/font3.ttf
    - family: font4
      fonts:
        - asset: assets/fonts/font4.ttf
    - family: tajwal
      fonts:
        - asset: assets/fonts/tajwal.ttf