name: Xcode - Build ios

on:
  push:
    branches: [ "config/nosos" ]
  pull_request:
    branches: [ "config/nosos" ]


jobs:
  build-and-analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # AdoptOpenJDK is now Eclipse Temurin
          java-version: '11'       # Use Java 11
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign